# Generated by Django 3.2.9 on 2022-03-09 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_deleted', models.DateTimeField(blank=True, editable=False, null=True)),
                ('unit_id', models.UUIDField(verbose_name='Unit')),
                ('nama', models.CharField(max_length=128, verbose_name='Nama')),
                ('jenis', models.CharField(max_length=16, verbose_name='Jenis')),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Unit',
            },
        ),
        migrations.CreateModel(
            name='SDM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_deleted', models.DateTimeField(blank=True, editable=False, null=True)),
                ('id_sdm', models.UUIDField(verbose_name='ID SDM')),
                ('nama_sdm', models.CharField(max_length=128, verbose_name='Nama SDM')),
                ('nidn', models.CharField(blank=True, max_length=16, null=True, verbose_name='NIDN')),
                ('nip', models.CharField(blank=True, max_length=16, null=True, verbose_name='NIP')),
                ('jenis_sdm', models.CharField(blank=True, max_length=16, null=True, verbose_name='Jenis SDM')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sister.unit')),
            ],
            options={
                'verbose_name': 'SDM',
                'verbose_name_plural': 'SDM',
            },
        ),
    ]
