# Generated by Django 3.2.9 on 2022-03-09 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sister', '0002_alter_unit_jenis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdm',
            name='nip',
            field=models.CharField(blank=True, max_length=28, null=True, verbose_name='NIP'),
        ),
    ]
