# Generated by Django 3.2.9 on 2022-03-11 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sister', '0005_sdm_slugname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sdm',
            options={'ordering': ['nama_sdm'], 'verbose_name': 'SDM', 'verbose_name_plural': 'SDM'},
        ),
        migrations.AddField(
            model_name='sdm',
            name='status',
            field=models.IntegerField(choices=[[1, 'Active'], [0, 'Inactive']], default=1, verbose_name='Status'),
        ),
    ]
