# Generated by Django 3.2.9 on 2022-03-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sister', '0006_auto_20220311_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdm',
            name='metadata',
            field=models.JSONField(blank=True, null=True, verbose_name='Metadata'),
        ),
    ]
