# Generated by Django 3.2.9 on 2022-03-15 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sister', '0009_auto_20220314_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_deleted', models.DateTimeField(blank=True, editable=False, null=True)),
                ('id_pt', models.UUIDField(editable=False, unique=True, verbose_name='ID PT')),
                ('kode', models.CharField(max_length=16, verbose_name='Kode')),
                ('nama', models.CharField(max_length=128, verbose_name='Nama')),
                ('telepon', models.CharField(blank=True, max_length=128, null=True, verbose_name='Telepon')),
                ('faximile', models.CharField(blank=True, max_length=128, null=True, verbose_name='Faximile')),
                ('email', models.CharField(blank=True, max_length=65, null=True, verbose_name='E-mail')),
                ('website', models.CharField(blank=True, max_length=64, null=True, verbose_name='Website')),
                ('jalan', models.CharField(blank=True, max_length=128, null=True, verbose_name='Jalan')),
                ('dusun', models.CharField(blank=True, max_length=128, null=True, verbose_name='Dusun')),
                ('rt', models.IntegerField(blank=True, null=True, verbose_name='RT')),
                ('rw', models.IntegerField(blank=True, null=True, verbose_name='RW')),
                ('kelurahan', models.CharField(blank=True, max_length=128, null=True, verbose_name='Kelurahan')),
                ('kode_pos', models.CharField(blank=True, max_length=16, null=True, verbose_name='Kode Pos')),
                ('nama_wilayah', models.CharField(blank=True, max_length=128, null=True, verbose_name='Nama Wilayah')),
                ('sk_pendirian', models.CharField(blank=True, max_length=128, null=True, verbose_name='SK Pendirian')),
                ('tanggal_sk', models.CharField(blank=True, max_length=128, null=True, verbose_name='Tanggal SK Pendirian')),
                ('status', models.CharField(blank=True, max_length=128, null=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'University',
                'verbose_name_plural': 'Universities',
            },
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['jenis'], 'verbose_name': 'Unit', 'verbose_name_plural': 'Unit'},
        ),
        migrations.AlterField(
            model_name='sdm',
            name='id_sdm',
            field=models.UUIDField(editable=False, verbose_name='ID SDM'),
        ),
        migrations.AlterField(
            model_name='sdm',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Metadata'),
        ),
        migrations.AlterField(
            model_name='sdm',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people', to='sister.unit'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_id',
            field=models.UUIDField(editable=False, verbose_name='Unit'),
        ),
    ]
