# Generated by Django 3.2.9 on 2022-01-19 01:46

import aurora.backend.library.models.renamer
import aurora.backend.library.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('name', models.SlugField(max_length=128, primary_key=True, serialize=False)),
                ('value', models.JSONField()),
                ('protected', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_deleted', models.DateTimeField(blank=True, editable=False, null=True)),
                ('picture', models.ImageField(blank=True, help_text=aurora.backend.library.validators.Validators.help_text, null=True, upload_to=aurora.backend.library.models.renamer.BaseModelRenamer.by_automatic_protected, validators=[aurora.backend.library.validators.Validators.validate], verbose_name='Picture')),
                ('email_confirmed', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_error', models.BooleanField(default=False)),
                ('password_reset', models.BooleanField(default=False)),
                ('subgroup', models.CharField(blank=True, max_length=32, null=True, verbose_name='Sub Group')),
                ('device', models.CharField(blank=True, max_length=256, null=True, verbose_name='Device')),
                ('browser', models.CharField(blank=True, max_length=512, null=True, verbose_name='Browser')),
                ('ip', models.CharField(blank=True, max_length=16, null=True, verbose_name='IP')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='property', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Property',
                'verbose_name_plural': 'User Properties',
            },
        ),
    ]
